#!/bin/bash

if [[ $# != 1 ]]
then
  echo "make_install /path/to/sensei/install"
  exit -1
fi

SENSEI_DIR=$1

rm -rf tmp_build_dir
mkdir tmp_build_dir
cd tmp_build_dir

cmake \
  -DSENSEI_DIR=${SENSEI_DIR}/lib/cmake \
  -DCMAKE_INSTALL_PREFIX=${SENSEI_DIR} \
   ../

make -j 1 install

cd ..

