set(SENSEI_ENABLE_PYTHON ON CACHE BOOL "")
set(SENSEI_PYTHON_VERSION 2 CACHE STRING "")

# ParaView no longer supports python 2
if (SENSEI_ENABLE_CATALYST)
  set(SENSEI_ENABLE_CATALYST_PYTHON OFF CACHE BOOL "")
endif ()
