# This is a Spack Environment file.
#
# It describes a set of packages to be installed, along with
# configuration settings.
spack:
  # add package specs to the `specs` list
  specs: [sensei@develop+adios2+ascent+hdf5+python+shared+vtkio+catalyst, lmod]
  view: false
  concretizer:
    unify: true
  packages:
    paraview:
      require: '@5.10.1 ~examples~qt+osmesa+shared+development_files use_vtkm=off
        build_edition=catalyst_rendering'
    mesa:
      require: ~glx~llvm
    openmpi:
      variants: ~static~vt
    all:
      require: target=x86_64
      providers:
        'mpi:': [openmpi]
    ascent:
      require: '@0.9.0 +vtkh'
