modules:
  default:
    enable:
    - lmod
    lmod:
      hash_length: 0
      all:
        autoload: 'direct'
      projections:
        all: '{name}/{version}'
    tcl:
      all:
        autoload: none
