packages:
  all:
    target: [haswell]
    providers:
      mpi: [openmpi]
  sensei:
    version: [develop]
    # TODO: Cannot build ascent until 0.8.0 is updated
    variants: +adios2+hdf5+python+vtkio+shared #+ascent
  paraview:
    version: [5.10.0]
    # Note: catalyst_rendering is required because SENSEI catalyst implies rendering
    variants: ~examples~qt+osmesa+shared+development_files use_vtkm=off build_edition=catalyst_rendering
  libunwind:
    variants: ~tests
  # Don't need GLX
  # Rendering performance is not important for CI testing so disable llvm
  mesa:
    variants: ~glx~llvm
  openmpi:
    variants: ~static~vt
