#ifndef SVTKPython_h
#define SVTKPython_h

/* TODO SWIG is not propagating these automatically */
#include <svtkObjectBase.h>
#include <svtkObject.h>
#include <svtkAbstractArray.h>
#include <svtkDataArray.h>
#include <svtkGenericDataArray.h>
#include <svtkAOSDataArrayTemplate.h>
/*#include <svtkArrayCoordinates.h>*/
/*#include <svtkArrayDispatch.h>*/
/*#include <svtkArrayExtents.h>
#include <svtkArrayExtentsList.h>*/
#include <svtkArray.h>
/*#include <svtkArrayInterpolate.h>*/
#include <svtkArrayIterator.h>
/*#include <svtkArrayIteratorIncludes.h>*/
#include <svtkArrayIteratorTemplate.h>
/*#include <svtkArrayPrint.h>
#include <svtkArrayRange.h>
#include <svtkArraySort.h>
#include <svtkArrayWeights.h>*/
#include <svtkBitArray.h>
#include <svtkBitArrayIterator.h>
#include <svtkCharArray.h>
#include <svtkDataArrayAccessor.h>
#include <svtkCollection.h>
#include <svtkCollectionIterator.h>
#include <svtkDataArrayCollection.h>
#include <svtkDataArrayCollectionIterator.h>
/*#include <svtkDataArrayIteratorMacro.h>
*#include <svtkDataArrayMeta.h>
#include <svtkDataArrayRange.h>
#include <svtkDataArraySelection.h>*/
#include <svtkDataArrayTemplate.h>
/*#include <svtkDataArrayTupleRange_AOS.h>
#include <svtkDataArrayTupleRange_Generic.h>
#include <svtkDataArrayValueRange_AOS.h>
#include <svtkDataArrayValueRange_Generic.h> */
/* #include <svtkDenseArray.h> */
#include <svtkDoubleArray.h>
#include <svtkFloatArray.h>
/*#include <svtkGenericDataArrayLookupHelper.h> */
#include <svtkIdTypeArray.h>
#include <svtkIntArray.h>
#include <svtkLongArray.h>
#include <svtkLongLongArray.h>
/*#include <svtkMappedDataArray.h>
#include <svtkScaledSOADataArrayTemplate.h> */
#include <svtkShortArray.h>
#include <svtkSignedCharArray.h>
#include <svtkSOADataArrayTemplate.h>
/*#include <svtkSortDataArray.h>
#include <svtkSparseArray.h>
#include <svtkStringArray.h>
#include <svtkTestDataArray.h> */
#include <svtkTypedArray.h>
#include <svtkTypedDataArray.h>
#include <svtkUnicodeStringArray.h>
#include <svtkUnsignedCharArray.h>
#include <svtkUnsignedIntArray.h>
#include <svtkUnsignedLongArray.h>
#include <svtkUnsignedLongLongArray.h>
#include <svtkUnsignedShortArray.h>
#include <svtkVariantArray.h>
#include <svtkVoidArray.h>
#include <svtkTypedDataArrayIterator.h>
#include <svtkCellArray.h>
#include <svtkFieldData.h>
#include <svtkCellTypes.h>
#include <svtkDataSetAttributes.h>
#include <svtkCellData.h>
#include <svtkPointData.h>
#include <svtkDataObject.h>
#include <svtkDataSet.h>
#include <svtkTable.h>
#include <svtkPointSet.h>
#include <svtkImageData.h>
#include <svtkRectilinearGrid.h>
#include <svtkStructuredGrid.h>
#include <svtkPolyData.h>
#include <svtkUnstructuredGridBase.h>
#include <svtkUnstructuredGrid.h>
#include <svtkCompositeDataSet.h>
#include <svtkDataObjectTree.h>
#include <svtkUniformGridAMR.h>
#include <svtkMultiBlockDataSet.h>
#include <svtkUniformGridAMR.h>
#include <svtkOverlappingAMR.h>
#include <svtkNonOverlappingAMR.h>
#include <svtkCompositeDataIterator.h>
#include <svtkDataObjectTreeIterator.h>
#include <svtkUniformGridAMRDataIterator.h>
/* #include <svtkGraph.h>
#include <svtkMolecule.h>
#include <svtkStructuredData.h>
#include <svtkGenericDataSet.h>
#include <svtkGenericAdaptorCell.h>
#include <svtkGenericAttribute.h>
#include <svtkBezierWedge.h>
#include <svtkReebGraphSimplificationMetric.h>
#include <svtkHyperTreeGrid.h>
#include <svtkSortFieldData.h>
#include <svtkCellIterator.h>
#include <svtkCellLinks.h>
#include <svtkAbstractCellLinks.h>
#include <svtkPartitionedDataSet.h>
#include <svtkDataSetCellIterator.h>
#include <svtkLocator.h>
#include <svtkDataSetAttributesFieldList.h>
#include <svtkStaticCellLinks.h>
#include <svtkSelectionNode.h>
#include <svtkPolyDataCollection.h>
#include <svtkIncrementalOctreePointLocator.h>
#include <svtkDataSetCollection.h>
#include <svtkMappedUnstructuredGrid.h>
#include <svtkGenericInterpolatedVelocityField.h>
#include <svtkImplicitDataSet.h>
#include <svtkBezierQuadrilateral.h>
#include <svtkStaticCellLinksTemplate.h>
#include <svtkArrayListTemplate.h>
#include <svtkBezierTriangle.h>
#include <svtkBezierHexahedron.h>
#include <svtkGenericCell.h>
#include <svtkIterativeClosestPointTransform.h>
#include <svtkUniformGrid.h>
#include <svtkFindCellStrategy.h>
#include <svtkCellType.h>
#include <svtkPath.h>
#include <svtkKdTree.h>
#include <svtkReebGraph.h>
#include <svtkExplicitStructuredGrid.h>
#include <svtkBezierTetra.h>
#include <svtkBezierCurve.h>
#include <svtkMultiPieceDataSet.h>
#include <svtkOctreePointLocator.h>
#include <svtkHierarchicalBoxDataIterator.h> */

#endif
