if(ENABLE_ADIOS1)
  find_package(ADIOS1 REQUIRED)

  add_library(sADIOS1 INTERFACE)
  target_link_libraries(sADIOS1 INTERFACE ${ADIOS1_LIBRARIES})
  target_include_directories(sADIOS1 SYSTEM INTERFACE ${ADIOS1_INCLUDE_DIRS})
  if(ADIOS1_DEFINITIONS)
    target_compile_definitions(sADIOS1 INTERFACE ${ADIOS1_DEFINITIONS})
  endif()
  install(TARGETS sADIOS1 EXPORT sADIOS1)
  install(EXPORT sADIOS1 DESTINATION ${sensei_CMAKE_INSTALL_CMAKEDIR}
    EXPORT_LINK_INTERFACE_LIBRARIES)
endif()
