if(ENABLE_ADIOS2)
  find_package(ADIOS2 REQUIRED)
  list(APPEND CMAKE_MODULE_PATH "${CMAKE_SOURCE_DIR}/CMake")

  add_library(sADIOS2 INTERFACE)
  target_link_libraries(sADIOS2 INTERFACE adios2::adios2)
  install(TARGETS sADIOS2 EXPORT sADIOS2)
  install(EXPORT sADIOS2 DESTINATION ${sensei_CMAKE_INSTALL_CMAKEDIR}
    EXPORT_LINK_INTERFACE_LIBRARIES)
endif()
