if(ENABLE_LIBSIM)
  find_package(LIBSIM REQUIRED)
  add_library(libsim INTERFACE)
  target_link_libraries(libsim INTERFACE ${LIBSIM_LIBRARIES})
  target_include_directories(libsim SYSTEM INTERFACE ${LIBSIM_INCLUDE_DIRS})
  install(TARGETS libsim EXPORT libsim)
  install(EXPORT libsim DESTINATION lib/cmake EXPORT_LINK_INTERFACE_LIBRARIES)
endif()
