if(ENABLE_OSPRAY)
  find_package(ospray REQUIRED)
  add_library(sOSPRay INTERFACE)
  message(STATUS "Using OSPRay library: \"${OSPRAY_LIBRARY}\"")
  target_link_libraries(sOSPRay INTERFACE ospray::ospray)
  target_include_directories(sOSPRay SYSTEM INTERFACE ${OSPRAY_INCLUDE_DIR})
  install(TARGETS sOSPRay EXPORT sOSPRay)
  install(EXPORT sOSPRay DESTINATION lib/cmake EXPORT_LINK_INTERFACE_LIBRARIES)
endif()
