# Mangled VTK
set(SVTK_LIBRARIES SVTK::CommonDataModel)

add_library(sSVTK INTERFACE)
target_link_libraries(sSVTK INTERFACE ${SVTK_LIBRARIES})

install(TARGETS sSVTK EXPORT sSVTK)
install(EXPORT sSVTK DESTINATION ${sensei_CMAKE_INSTALL_CMAKEDIR}
  EXPORT_LINK_INTERFACE_LIBRARIES)
