set(SENSEI_VTKM_COMPONENTS Base)
if (ENABLE_VTKM_RENDERING)
  list(APPEND SENSEI_VTKM_COMPONENTS Rendering)
endif()

if (ENABLE_VTKM)
  find_package(VTKm QUIET REQUIRED COMPONENTS ${SENSEI_VTKM_COMPONENTS})
endif()
