name: GitHub Actions

on:
  pull_request:
    branches:
      - main
      - develop

jobs:
  linux-ecp:
    runs-on: ubuntu-latest
    env:
      LAUNCHER: .github/ci/docker/spack/launcher.sh
      CMAKE_CONFIGURATION: linux_ecp
    container:
      image: senseiinsitu/sensei-ci:2021.07.08
      options: --user=root

    steps:
    - uses: actions/checkout@v2
    - name: Configure
      run: ${{ env.LAUNCHER }} ctest -VV -S .github/ci/ctest_configure.cmake
    - name: Build
      run: ${{ env.LAUNCHER }} ctest -VV -S .github/ci/ctest_build.cmake
    - name: Test
      run: ${{ env.LAUNCHER }} ctest -VV -S .github/ci/ctest_test.cmake
    - name: 'Upload Artifacts'
      uses: actions/upload-artifact@v2
      with:
        name: ${{ env.CMAKE_CONFIGURATION }}_${{ env.GITHUB_JOB }}
        path: build
        retention-days: 1
